name: StudentGradeActions
on: workflow_dispatch
env:
  AWS_REGION: us-east-1
jobs:
  Run-Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run sed command
        run: |
        sed -i "s/^jdbc.username.*$/jdbc.username\=${{ secrets.RDS_USER }}/" src/main/resources/application.properties
        sed -i "s/^jdbc.password.*$/jdbc.password\=${{ secrets.RDS_PASS }}/" src/main/resources/application.properties
        sed -i "s/db01/${{ secrets.RDS_ENDPOINT }}/" src/main/resources/application.properties

