name: TestGradeActions
# on: workflow_dispatch
on:
  push:
    branches:
    - javabanking
env:
  AWS_REGION: us-east-1
  RDS_ENDPOINTS: javademoapp
  DB_NAME: javadb
  DB_USER: admin
  DB_PASS: admin
  EMAIL_USER: admin
  EMAIL_PASS: admin
jobs:
  Run-Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run sed command
        run: |
          sed -i 's/^spring.datasource.url.*/spring.datasource.url=jdbc:mysql\:\/\/${{env.RDS_ENDPOINTS}}\/${{env.DB_NAME}}/' src/main/resources/application.properties
          sed -i 's/^spring.datasource.username.*/spring.datasource.username=${{env.DB_USER}}/' src/main/resources/application.properties
          sed -i 's/^spring.datasource.password.*/spring.datasource.password=${{env.DB_PASS}}/' src/main/resources/application.properties
          sed -i 's/^spring.mail.username.*/spring.mail.username=${{env.EMAIL_USER}}/' src/main/resources/application.properties
          sed -i 's/^spring.mail.password.*/spring.mail.password=${{env.EMAIL_PASS}}/' src/main/resources/application.properties
          echo
          echo
          cat src/main/resources/application.properties